from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TASK6 = ROOT / "task6"
OUTPUT_DIR = TASK6 / "outputs"
DESIGN_DIR = TASK6 / "design"
HTML_PATH = DESIGN_DIR / "ml_strategy_panel.html"
INDEX_PATH = TASK6 / "index.html"


HTML_TEMPLATE = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Task6 机器学习选股策略回测</title>
  <style>
    :root { --ink:#172033; --muted:#64748b; --line:#d9e2ec; --bg:#f4f7fb; --panel:#fff; --blue:#1d4ed8; --green:#15803d; --orange:#c2410c; --red:#b91c1c; --violet:#7e22ce; --teal:#0f766e; }
    * { box-sizing:border-box; } body { margin:0; background:var(--bg); color:var(--ink); font:14px/1.45 "Microsoft YaHei",Arial,sans-serif; letter-spacing:0; }
    header { background:#14213d; color:#fff; padding:16px 22px; display:flex; gap:20px; align-items:center; justify-content:space-between; } h1 { margin:0; font-size:20px; } h2 { margin:0; font-size:16px; } header p,.muted { color:var(--muted); font-size:12px; } header p { color:#cbd5e1; margin:3px 0 0; } .controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.range-label{display:grid;gap:3px;color:#dbeafe;font-size:12px}.range-label input{width:140px}
    main { width:min(1520px,100%); margin:0 auto; padding:16px; display:grid; gap:16px; } .grid { display:grid; grid-template-columns:repeat(12,minmax(0,1fr)); gap:16px; } .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:14px; min-width:0; } .span-3{grid-column:span 3}.span-4{grid-column:span 4}.span-5{grid-column:span 5}.span-6{grid-column:span 6}.span-7{grid-column:span 7}.span-8{grid-column:span 8}.span-12{grid-column:span 12}
    .title { display:flex; align-items:center; justify-content:space-between; gap:10px; margin-bottom:10px; } .kpi { min-height:92px; display:grid; align-content:space-between; } .kpi strong { font-size:25px; } .kpi span { color:var(--muted); font-size:12px; } select { height:34px; border:1px solid #586579; border-radius:6px; padding:0 9px; color:#fff; background:#263653; font:inherit; }
    .chart { height:330px; overflow:hidden; } .chart.small { height:275px; } svg { display:block; width:100%; height:100%; } table { border-collapse:collapse; width:100%; font-size:12px; } th,td { padding:8px 7px; border-bottom:1px solid #e7edf4; text-align:right; white-space:nowrap; } th { color:#475569; background:#f8fafc; } th:first-child,td:first-child{text-align:left}.scroll { overflow:auto; max-height:360px; } .formula { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:8px; } .formula div { padding:9px; border:1px solid #e5ebf2; border-radius:6px; background:#fbfdff; } .formula strong { color:var(--blue); display:block; font-size:17px; }
    .note { color:#334155; background:#eff6ff; border-left:3px solid var(--blue); padding:10px 12px; font-size:12px; } .heat td { min-width:84px; } .legend { display:flex; gap:13px; flex-wrap:wrap; color:#475569; font-size:12px; } .legend span::before { content:""; display:inline-block; width:10px; height:10px; border-radius:50%; margin-right:5px; background:var(--c); } .empty { color:var(--muted); padding:30px; text-align:center; }
    @media(max-width:1000px){.span-3,.span-4,.span-5,.span-6,.span-7,.span-8{grid-column:span 12}} @media(max-width:600px){header{align-items:flex-start;flex-direction:column}.formula{grid-template-columns:1fr}.chart{height:280px}main{padding:10px}}
  </style>
</head>
<body>
<script>const APP_DATA = __APP_DATA__;</script>
<header><div><h1>Task6 机器学习选股策略回测</h1><p>复权总收益口径 · 四模型、组合策略与双基准对比</p></div><div class="controls"><label>单模型明细 <select id="modelSelect"></select></label><label class="range-label">分类阈值 <span id="thresholdValue">0.50</span><input id="threshold" type="range" min="0" max="1" step="0.01" value="0.50"></label></div></header>
<main>
  <div class="note" id="priceNote"></div>
  <section class="grid"><div class="panel span-3 kpi"><span id="equalComboLabel">当前模型 Top20 等资金</span><strong id="equalCombo">-</strong><span>20 只股票各配 5%</span></div><div class="panel span-3 kpi"><span id="weightedComboLabel">当前模型 Top20 预测值加权</span><strong id="weightedCombo">-</strong><span>按同模型预测分数分位数加权</span></div><div class="panel span-3 kpi"><span>样本池等权基准</span><strong id="marketEqual">-</strong><span>测试期全部可交易样本</span></div><div class="panel span-3 kpi"><span>沪深300基准</span><strong id="marketHs300">-</strong><span>000300.SH 价格指数</span></div></section>
  <section class="grid"><div class="panel span-8"><div class="title"><h2>四模型等资金策略与市场基准净值曲线</h2><span class="muted">从测试期起点 1.00 开始</span></div><div class="chart" id="comparisonChart"></div></div><div class="panel span-4"><div class="title"><h2>各模型：等资金 vs 预测值加权</h2><span class="muted">同一模型、同一 Top20 股票池</span></div><div class="scroll" id="ensembleTable"></div></div></section>
  <section class="grid"><div class="panel span-8"><div class="title"><h2>变量重要性跨模型比较</h2><span class="muted">每列已归一化，便于横向阅读</span></div><div class="scroll" id="importanceHeatmap"></div></div><div class="panel span-4"><div class="title"><h2>增长综合分构成</h2><span class="muted">同一期横截面分位数</span></div><div class="formula" id="growthFormula"></div></div></section>
  <section class="grid"><div class="panel span-3 kpi"><span>当前模型</span><strong id="modelName">-</strong><span>测试集表现</span></div><div class="panel span-3 kpi"><span>策略累计收益</span><strong id="strategyReturn">-</strong><span>Top 20 等权</span></div><div class="panel span-3 kpi"><span>相对样本池超额</span><strong id="excessEqual">-</strong><span>扣成本后比较</span></div><div class="panel span-3 kpi"><span>相对沪深300超额</span><strong id="excessHs300">-</strong><span>指数价格收益基准</span></div></section>
  <section class="grid"><div class="panel span-7"><div class="title"><h2>当前模型净值与基准</h2><span class="muted">策略、样本池等权、沪深300</span></div><div class="chart small" id="modelNavChart"></div></div><div class="panel span-5"><div class="title"><h2>当前模型季度收益</h2><span class="muted">扣成本后</span></div><div class="chart small" id="quarterChart"></div></div></section>
  <section class="grid"><div class="panel span-7"><div class="title"><h2 id="rocTitle">ROC 曲线</h2><span class="muted">测试集，ROC/AUC 不随阈值改变</span></div><div class="chart small" id="rocChart"></div></div><div class="panel span-5"><div class="title"><h2>混淆矩阵</h2><span class="muted" id="classMetricNote">预测阈值 0.50</span></div><div class="chart small" id="confusionChart"></div></div></section>
  <section class="grid"><div class="panel span-6"><div class="title"><h2>当前模型变量重要性</h2><span class="muted">线性模型为绝对系数；树模型为分裂贡献</span></div><div class="chart" id="importanceChart"></div></div><div class="panel span-6"><div class="title"><h2>当前模型 Top 20 持仓</h2><span class="muted">测试期</span></div><div class="scroll" id="holdingsTable"></div></div></section>
  <section class="panel"><div class="title"><h2>成本与收益率口径</h2><span class="muted">收益与目标变量统一</span></div><div id="costTable"></div></section>
</main>
<script>
const $=id=>document.getElementById(id), pct=v=>Number.isFinite(Number(v))?(Number(v)*100).toFixed(2)+'%':'-', num=(v,d=4)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'-';
const COLORS=['#1d4ed8','#15803d','#c2410c','#7e22ce','#0f766e','#b91c1c','#475569','#0891b2'];
const models=Object.keys(APP_DATA.model_labels), labels=APP_DATA.model_labels;
function path(points,key,x,y){return points.map((p,i)=>(i?'L':'M')+' '+x(i)+' '+y(p[key])).join(' ')}
function modelRows(model){return APP_DATA.quarterly_returns.filter(r=>r.model===model).sort((a,b)=>String(a.Date).localeCompare(String(b.Date)))}
function navRows(rows,fields){let state=Object.fromEntries(fields.map(k=>[k,1]));return [{Date:'测试期起点',...state},...rows.map(r=>{fields.forEach(k=>state[k]*=1+Number(r[k]));return {Date:r.Date,...state}})]}
function lineChart(host, series, height=330){const dates=series[0]?.points||[];if(!dates.length){$(host).innerHTML='<div class="empty">暂无数据</div>';return}const vals=series.flatMap(s=>s.points.map(p=>p.value));const lo=Math.min(...vals,0.9),hi=Math.max(...vals,1.1),x=i=>55+(dates.length===1?190:i*395/(dates.length-1)),y=v=>248-(v-lo)/(hi-lo||1)*190;let marks=`<line x1="55" y1="248" x2="450" y2="248" stroke="#cbd5e1"/><line x1="55" y1="42" x2="55" y2="248" stroke="#cbd5e1"/><text x="10" y="50" font-size="11">${hi.toFixed(2)}</text><text x="10" y="248" font-size="11">${lo.toFixed(2)}</text>`;series.forEach((s,i)=>{marks+=`<path d="${s.points.map((p,j)=>(j?'L':'M')+' '+x(j)+' '+y(p.value)).join(' ')}" fill="none" stroke="${s.color}" stroke-width="${s.emphasis?3.4:2.1}"/><text x="${x(dates.length-1)+4}" y="${y(s.points.at(-1).value)+3}" font-size="10" fill="${s.color}">${s.label}</text>`});$(host).innerHTML=`<svg viewBox="0 0 510 285" role="img" aria-label="净值曲线">${marks}<text x="245" y="275" text-anchor="middle" font-size="11">测试期季度</text></svg>`}
function baseBenchmark(){const r=APP_DATA.quarterly_returns[0];return r?{equal:r.equal_weight_return,hs300:r.hs300_return}:{} }
function renderComparison(){const base={};for(const row of APP_DATA.quarterly_returns){if(!base[row.Date])base[row.Date]={Date:row.Date,equal_weight_return:row.equal_weight_return,hs300_return:row.hs300_return}}const series=models.map((m,i)=>{let n=1;const points=[{Date:'起点',value:1},...modelRows(m).map(r=>({Date:r.Date,value:n*=1+Number(r.strategy_return)}))];return {label:labels[m],color:COLORS[i],points,emphasis:false};});let e=1,h=1;const benchmarkRows=Object.values(base).sort((a,b)=>String(a.Date).localeCompare(String(b.Date)));series.push({label:'样本池等权',color:'#475569',points:[{Date:'起点',value:1},...benchmarkRows.map(r=>({Date:r.Date,value:e*=1+Number(r.equal_weight_return)}))]});series.push({label:'沪深300',color:'#0891b2',points:[{Date:'起点',value:1},...benchmarkRows.map(r=>({Date:r.Date,value:h*=1+Number(r.hs300_return)}))]});lineChart('comparisonChart',series);}
function renderEnsembles(){const rows=APP_DATA.ensemble_metrics||[];$('ensembleTable').innerHTML=`<table><thead><tr><th>模型</th><th>权重</th><th>累计收益</th><th>样本池超额</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.model_label}</td><td>${r.scheme==='equal_weight'?'等资金':'预测值加权'}</td><td>${pct(r.strategy_return)}</td><td>${pct(r.excess_equal)}</td></tr>`).join('')}</tbody></table>`;const bm=baseBenchmark();$('marketEqual').textContent=pct(bm.equal);$('marketHs300').textContent=pct(bm.hs300);}
function renderHeatmap(){const features=[...new Set(APP_DATA.feature_importance.map(r=>r.feature))];let html='<table class="heat"><thead><tr><th>变量</th>'+models.map(m=>`<th>${labels[m]}</th>`).join('')+'</tr></thead><tbody>';for(const f of features){html+='<tr><td>'+f+'</td>'+models.map(m=>{const r=APP_DATA.feature_importance.find(x=>x.model===m&&x.feature===f),v=Number(r?.importance_normalized||0),a=(0.1+v*0.8).toFixed(2);return `<td style="background:rgba(29,78,216,${a})">${pct(v)}</td>`}).join('')+'</tr>'}html+='</tbody></table>';$('importanceHeatmap').innerHTML=html;}
function renderGrowth(){$('growthFormula').innerHTML=APP_DATA.growth_score_formula.map(x=>`<div><strong>${Math.round(x.weight*100)}%</strong><span>${x.feature}</span></div>`).join('')}
function thresholdMetric(model){const t=Number($('threshold').value).toFixed(2);return APP_DATA.threshold_metrics.find(x=>x.model===model&&Number(x.threshold).toFixed(2)===t)||{}}
function renderModel(){const m=$('modelSelect').value, metric=APP_DATA.backtest_metrics.find(x=>x.model===m)||{},cm=thresholdMetric(m),weights=APP_DATA.ensemble_metrics.filter(x=>x.model===m),eq=weights.find(x=>x.scheme==='equal_weight'),wt=weights.find(x=>x.scheme==='prediction_weighted');$('modelName').textContent=labels[m];$('strategyReturn').textContent=pct(metric.strategy_return);$('excessEqual').textContent=pct(metric.excess_equal);$('excessHs300').textContent=pct(metric.excess_hs300);$('equalComboLabel').textContent=labels[m]+' Top20 等资金';$('weightedComboLabel').textContent=labels[m]+' Top20 预测值加权';$('equalCombo').textContent=pct(eq?.strategy_return);$('weightedCombo').textContent=pct(wt?.strategy_return);$('rocTitle').textContent=labels[m]+' ROC 曲线';$('classMetricNote').textContent=`阈值 ${Number($('threshold').value).toFixed(2)} · 准确率 ${pct(cm.accuracy)} · 精确率 ${pct(cm.precision)} · 召回率 ${pct(cm.recall)} · F1 ${num(cm.f1,3)}`;renderModelNav(m);renderQuarter(m);renderRoc(m);renderConfusion(cm);renderImportance(m);renderHoldings(m)}
function renderModelNav(m){const rows=modelRows(m),n=navRows(rows,['strategy_return','prediction_weighted_return','equal_weight_return','hs300_return']);lineChart('modelNavChart',[{label:'Top20 等资金',color:COLORS[0],points:n.map(p=>({value:p.strategy_return}))},{label:'Top20 预测值加权',color:COLORS[3],points:n.map(p=>({value:p.prediction_weighted_return}))},{label:'样本池等权',color:COLORS[1],points:n.map(p=>({value:p.equal_weight_return}))},{label:'沪深300',color:COLORS[2],points:n.map(p=>({value:p.hs300_return}))}],275)}
function renderQuarter(m){const rows=modelRows(m),vals=rows.flatMap(r=>['strategy_return','prediction_weighted_return','equal_weight_return','hs300_return'].map(k=>Number(r[k]))),lo=Math.min(0,...vals),hi=Math.max(0,...vals),y=v=>215-(v-lo)/(hi-lo||1)*165,z=y(0);let marks=`<line x1="55" y1="${z}" x2="455" y2="${z}" stroke="#cbd5e1"/>`;rows.forEach((r,i)=>[['strategy_return',COLORS[0]],['prediction_weighted_return',COLORS[3]],['equal_weight_return',COLORS[1]],['hs300_return',COLORS[2]]].forEach(([k,c],j)=>{let yy=y(Number(r[k])),x=75+i*135+j*28;marks+=`<rect x="${x}" y="${Math.min(yy,z)}" width="21" height="${Math.abs(z-yy)}" fill="${c}"/>`}));$('quarterChart').innerHTML=`<svg viewBox="0 0 500 255">${marks}<text x="80" y="240" font-size="11">等资金 / 预测值加权 / 样本池 / 沪深300</text></svg>`}
function renderRoc(m){const points=APP_DATA.roc_points[m]||[],d=points.map((p,i)=>(i?'L':'M')+' '+(58+p.fpr*370)+' '+(232-p.tpr*180)).join(' ');$('rocChart').innerHTML=`<svg viewBox="0 0 480 270"><line x1="58" y1="232" x2="428" y2="232" stroke="#cbd5e1"/><line x1="58" y1="52" x2="58" y2="232" stroke="#cbd5e1"/><line x1="58" y1="232" x2="428" y2="52" stroke="#cbd5e1" stroke-dasharray="5 5"/><path d="${d}" fill="none" stroke="${COLORS[0]}" stroke-width="3"/><text x="243" y="258" text-anchor="middle">假阳性率 FPR</text><text x="15" y="145" transform="rotate(-90 15 145)" text-anchor="middle">真正率 TPR</text></svg>`}
function renderConfusion(m){const cells=[['TN',m.tn,'#dbeafe'],['FP',m.fp,'#fee2e2'],['FN',m.fn,'#ffedd5'],['TP',m.tp,'#dcfce7']];$('confusionChart').innerHTML=`<svg viewBox="0 0 420 270">${cells.map((c,i)=>{let x=78+(i%2)*140,y=48+Math.floor(i/2)*95;return `<rect x="${x}" y="${y}" width="120" height="76" rx="5" fill="${c[2]}"/><text x="${x+60}" y="${y+28}" text-anchor="middle" font-weight="700">${c[0]}</text><text x="${x+60}" y="${y+55}" text-anchor="middle" font-size="20">${c[1]??'-'}</text>`}).join('')}<text x="210" y="25" text-anchor="middle">预测类别</text></svg>`}
function renderImportance(m){const rows=APP_DATA.feature_importance.filter(r=>r.model===m).sort((a,b)=>b.importance-a.importance),max=Math.max(...rows.map(r=>Number(r.importance)),.0001);$('importanceChart').innerHTML=`<svg viewBox="0 0 710 330">${rows.map((r,i)=>{let y=22+i*40,w=Number(r.importance)/max*330;return `<text x="8" y="${y+14}" font-size="12">${r.feature}</text><rect x="255" y="${y}" width="${w}" height="18" fill="${COLORS[0]}"/><text x="${265+w}" y="${y+14}" font-size="12">${num(r.importance,3)}</text>`}).join('')}</svg>`}
function renderHoldings(m){const rows=APP_DATA.holdings.filter(r=>r.model===m).sort((a,b)=>a.rank-b.rank);$('holdingsTable').innerHTML=`<table><thead><tr><th>季度</th><th>排名</th><th>代码</th><th>预测分数</th><th>预测权重</th><th>扣成本后</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${String(r.Date).slice(0,10)}</td><td>${r.rank}</td><td>${r.ts_code||r.Code}</td><td>${num(r.score)}</td><td>${pct(r.prediction_weight)}</td><td>${pct(r.net_return)}</td></tr>`).join('')}</tbody></table>`}
function renderNotes(){const p=APP_DATA.price_info,c=APP_DATA.costs;$('priceNote').textContent=`收益口径：${p.price_basis}。样本价格匹配 ${pct(p.price_match_rate)}（${p.matched_rows}/${p.total_rows}）；沪深300作为价格指数基准。`;$('costTable').innerHTML=`<table><tbody><tr><td>买入成本率</td><td>${num(c.buy_cost_rate,7)}</td></tr><tr><td>卖出成本率</td><td>${num(c.sell_cost_rate,7)}</td></tr><tr><td>总收益公式</td><td>${p.return_formula}</td></tr><tr><td>策略选股</td><td>每期按模型得分选择 Top ${c.top_n}，单模型策略等权；组合策略见顶部比较表。</td></tr></tbody></table>`}
function setup(){$('modelSelect').innerHTML=models.map(m=>`<option value="${m}">${labels[m]}</option>`).join('');$('modelSelect').value='random_forest';$('modelSelect').addEventListener('change',renderModel);$('threshold').addEventListener('input',()=>{$('thresholdValue').textContent=Number($('threshold').value).toFixed(2);renderModel()});renderNotes();renderEnsembles();renderComparison();renderHeatmap();renderGrowth();renderModel()}setup();
</script></body></html>"""

INDEX_TEMPLATE = """<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; url=design/ml_strategy_panel.html\"><title>Task6</title></head><body><a href=\"design/ml_strategy_panel.html\">打开 Task6 机器学习选股策略回测</a></body></html>"""


def main() -> None:
    DESIGN_DIR.mkdir(parents=True, exist_ok=True)
    payload = json.loads((OUTPUT_DIR / "strategy_payload.json").read_text(encoding="utf-8"))
    HTML_PATH.write_text(HTML_TEMPLATE.replace("__APP_DATA__", json.dumps(payload, ensure_ascii=False, separators=(",", ":"))), encoding="utf-8")
    INDEX_PATH.write_text(INDEX_TEMPLATE, encoding="utf-8")
    print(HTML_PATH)
    print(INDEX_PATH)


if __name__ == "__main__":
    main()
